AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Get news or new CFN releases'

Parameters:
  TelegramBotToken:
    Type: String
    NoEcho: true
  TelegramChatId:
    Type: String

Metadata:
  AWS::ServerlessRepo::Application:
    Name: cfn-news-to-telegram
    Description: Send Cloudformation feature releases to Telegram in a private chat on a weekly basis (Every Saturday at 17:00 UTC).
    Author: jeshan
    SpdxLicenseId: BSD-2-Clause
    LicenseUrl: ../LICENCE.txt
    ReadmeUrl: ../README.md
    Labels: ['cloudformation', 'telegram']
    HomePageUrl: https://github.com/jeshan/cfn-news-to-telegram
    SemanticVersion: '0.1.1'
    SourceCodeUrl: https://github.com/jeshan/cfn-news-to-telegram

Resources:
  Fn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../cfn-news/code
      Handler: index.handler
      Runtime: python3.6
      Timeout: 120
      Environment:
        Variables:
          TELEGRAM_BOT_TOKEN: !Ref TelegramBotToken
          TELEGRAM_CHAT_ID: !Ref TelegramChatId
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 17 ? * SAT *) # Saturdays at 17:00 UTC
